version: "3.8"
services:
  app:
    build:
      args:
        user: familytree365
        uid: 1000
      context: ./
      dockerfile: .docker/Dockerfile
    image: familytree365/backend
    container_name: familytree365-backend
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - familytree365
  nginx:
    image: nginx:1.17-alpine
    container_name: familytree365-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - familytree365

networks:
  familytree365:
    driver: bridge
